language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
  fast_finish: true

install:
  - pwsh -f "${TRAVIS_BUILD_DIR}/InstallDependencies.ps1"

script:
  - pwsh -f "${TRAVIS_BUILD_DIR}/Orchestration/Tests/UnitTests/RunAll.ps1"