#The ci pipeline to be use for each module
name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:rr)

variables:
  ModuleName: _moduleName_
  ModuleVersion: _moduleVersion_
  RepoName: azure-devops
  ModulePath: modules/$(ModuleName)/$(ModuleVersion)
  ArtifactName: contents

resources:
  repositories:
    - repository: main
      type: git
      name: '$(RepoName)'

trigger:
  branches:
    include:
      - master
      - '*'
  paths:
    include:
      - modules/_moduleName_/_moduleVersion_

jobs:
- job: BuildModule
  displayName: Build Module
  pool:
    vmImage: ubuntu-16.04
  workspace:
    clean: all
  
  steps:
  - template: /azure-devops/ci/buildmodule.yaml
    parameters:
      ModulePath: $(ModulePath)
      ArtifactName: $(ArtifactName)