= On-premises connectivity requirements

The toolkit assumes you will be connecting your shared services to an on-premises network with domain services running. You can use one the following methods.

[options="header",cols=","]
|===
| Connection method | Description
| https://docs.microsoft.com/azure/vpn-gateway/vpn-gateway-about-vpngateways[Azure VPN gateway]
| VPN gateways create a site-to-site connection that passes encrypted traffic over the public Internet. This method requires a https://docs.microsoft.com/azure/vpn-gateway/vpn-gateway-about-vpn-devices[supported VPN device] hosted in your on-premises data center that the Azure VPN gateway deployed in the shared services environment can connect to.

| https://docs.microsoft.com/azure/expressroute/[ExpressRoute]
| ExpressRoute uses a dedicated, private connection facilitated by a connectivity provider. For security and performance purposes, most organizations prefer ExpressRoute connections. Since these can take several weeks to provision, VPN gateways can be used as a bootstrap connection until an ExpressRoute connection is available. If you plan to use an ExpressRoute with a toolkit deployment, it must already exist. It cannot be provisioned as part of a toolkit deployment like a VPN gateway can.

See https://docs.microsoft.com/azure/expressroute/expressroute-howto-circuit-portal-resource-manager[Create and modify an ExpressRoute circuit] for details on establishing an ExpressRoute.

|===

For testing purposes, the toolkit includes an archetype for a link:../archetypes/on-premises/overview.adoc[simulated on-premises environment] hosted on Azure. The toolkit will automatically connect this environment to your shared services network using a VPN gateway (Vnet-2-Vnet connection type).

If you plan to connect an actual on-premises environment, you will need to manually configure ExpressRoute or VPN connections after creating the shared services virtual network. You must establish these connections before any resources deployed by the toolkit can join the on-premises domain or make use of any other on-premises resources.

See https://docs.microsoft.com/azure/architecture/reference-architectures/hybrid-networking/[Choose a solution for connecting an on-premises network to Azure] in the Azure Architecture Center for additional guidance.
