from enum import Enum

class IntegrationType(Enum):
    BILLING_CLIENT_SDK=1
    MANAGEMENT_GROUP_CLIENT_SDK=2
    MANAGEMENT_LOCK_CLIENT_SDK=3
    POLICY_CLIENT_SDK=4
    RESOURCE_MANAGEMENT_CLIENT_SDK=5
    SUBSCRIPTION_CLIENT_SDK=6
    AAD_CLIENT_CLI=7
    KEYVAULT_CLIENT_CLI=8
    RBAC_CLIENT_CLI=9
    RESOURCE_MANAGEMENT_CLIENT_CLI=10
    SUBSCRIPTION_CLIENT_CLI=11