from enum import Enum

class SdkType(Enum):
    RESOURCE_MANAGEMENT_CLIENT=1,
    BLOB_STORAGE_CLIENT=2,
    POLICY_CLIENT=3,
    RESOURCE_LOCK_CLIENT = 4,
    SUBSCRIPTION_CLIENT = 5,
    MANAGEMENT_GROUP_CLIENT = 6,
    BILLING_CLIENT = 7