= File formatting in the documentation

The documentation files within this project use the following two file formats:

== Markdown

Many of the files in the toolkit's documentation use the Markdown format. These files use the `.md` file extension.

Useful links for authoring in Markdown:

- https://guides.github.com/features/mastering-markdown/[GitHub Guides: Mastering Markdown]  

== AsciiDoc format
Many of the files in the toolkit's documentation use the https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc format]. These files use the `.adoc` file extension. This format was chosen over markdown because it is easier to manage certain structures such as tables and notes. Currently, the documentation is a mixture of markdown and AsciiDoc since we only converted files that required the new format.

Useful links for authoring in AsciiDoc:

- https://powerman.name/doc/asciidoc[Powerman's AsciiDoc cheatsheet]
- https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
- https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide]

When editing AsciiDoc (`.adoc` files) using https://code.visualstudio.com[Visual Studio Code], the https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[AsciiDoc] extension from João Pinto can be installed to give syntax highlighting and preview support.