= vdc.py

_Deploy archetypes and modules into a subscription_

âœ link:readme.md[>> View other scripts]

.Before Using
[NOTE] 
====
- link:script-auth.adoc[Authenticate with Azure] before invoking the script.
- Be sure that you are in the root folder of the toolkit.
- The permissions required to execute this script are determined by the modules being deployed.
====

This script deploys an link:../understand/toolkit.md#archetypes[_archetype_], or a specified link:../understand/toolkit.md#modules[_module_] within an archetype, to the target subscription. It also assigns the policies located at link:..\..\modules\policies\subscription\1.0\arm.policies.json[`modules\policies\subscription\1.0\arm.policies.json`] to the target subscription. Policies included within the specified modules are assigned at the resource group level.
All of the policy definitions are located in the target subscription.

NOTE: This script does not create management groups or assign policies to management groups.

.Docker
[source,bash]
python vdc.py {command} {environment type} {arguments}

.Linux/OSX
[source,bash]
python3 vdc.py {command} {environment type} {arguments}

.Windows
[source,cmd]
py vdc.py {command} {environment type} {arguments}

== Commands

There are two commands you can supply. 

- `create` executes a deployment of an archetype or a specified module with an archetype. 
- `validate` executes a link:../use/deployment-validation.adoc[validation of the deployment]. Note that some resources may actually be deployed during a validation.

== Environment types

The environment type is either `shared-services`, `on-premises`, or `workload`  indicating which type of the archetype you are deploying. More details about environment types are link:../understand/environment-types.md[here].

== Arguments

There are several required and optional arguments that you can pass for a deployment:

[options="header",cols="<.< 35% a,<.< 5%,<.< 60%"]
|===
| Argument | Required? | Description

| [source]
----
-path
--configuration-file-path
----
| Required
| Path pointing to the root parameters file for the archetype you want to deploy.

| [source]
----
-m
--module
----
| Optional
| Specifies a single module within the archetype to deploy. This value is limited to the list of modules in the `orchestration.modules-to-deploy` array of the archetype's configuration file.

If this argument is not specified, the script processes each of the resources in the order they appear in the array.

In a production environment, you should follow separation of responsibilities. This means that a single users is not likely to have rights to deploy all of the modules in an archetype.

This argument should not be used when deploying a simulated on-premises environment.

| [source]
----
-rg
--resource-group 
----

| Optional
| Specifies the name of the resource group where the resources will be created. If the group does not exist, the script creates it. If this parameter is not specified, the script creates a resource group named using a combination of the organization name you set in your main parameters file and the resource type being deployed.

| [source]
----
-l
--location
----

| Optional
| Specifies the Azure region to use when deploying resources. If the region value in your main parameters file is blank, this parameter is required.

| [source]
----
--deploy-dependencies
----

| Optional
| Deploy module dependencies. If present, the script deploys any modules that are listed as dependencies for the module you're currently deploying. The dependencies for a modules are defined in each archetype's configuration file. Meaning that the dependencies for a module can vary by archetype. Look for the `dependencies` array in the module configuration in the archetype configuration file.

If the user running this command does not have the correct permissions to run all of the dependent modules, setting this argument can generate errors. In addition, if the dependent modules have already been run for this deployment, the script *redeploys* these resources using the latest parameter values.

| [source]
----
--delete-validation-resources
----

| Optional
| Deletes resources that are deployed during a `validate` command. This is only recommended when there is not a existing deployment. 

| [source]
----
--upload-scripts
----

| Optional
| If present, the link:../../scripts[scripts] folder gets uploaded to the default storage account. Resource deployments will only upload the common toolkit scripts to Azure storage if this argument is included. It's important to use this when deploying any resources that depend on scripts to finish their configuration, like ADDS servers and NVAs. Note this will overwrite any existing scripts previously uploaded.

| [source]
----
--prevent-vdc-storage-creation
----
| Optional
| By default, deployments will create a new storage account for output and scripts if one does not exist. Including this argument will prevent this, and only deploy if the target storage account exists. Storage account name is set in the archetype configuration file in the `vdc-storage-account-name` parameter.

|===

== Example

This example deploys the paas archetype and uploads the scripts folder.

.Docker
[source,bash]
python vdc.py create workload -path ./archetypes/paas/archetype.json --upload-scripts

.Linux/OSX
[source,bash]
python3 vdc.py create workload -path ./archetypes/paas/archetype.json --upload-scripts

.Windows
[source,cmd]
py vdc.py create workload -path ./archetypes/paas/archetype.json --upload-scripts